### ISSUE TITLE
Create on config file an entrance to save logs

### ISSUE THREAD

**Issue by rogersilvasouza** [astrolink/pluto#1]
On discuss with @phgaliotti verify a necessity to create a save logs on database, but I need think is very best form to made with without affect projects.

Primary example of entrance on config: 

```yaml
connection:
  name: "MySQL"
  host: "127.0.0.1"
  port: "3306"
  database: "astrolink"
  username: "root"
  password: ""
  
logs:
  database: "mysql"
  table: "pluto_logs" 
```

What team think about this?
